---
title: "DataMemo"
output: html_document
date: "2022-10-03"
---

All of the data is collected from Yahoo Finance. Since the earliest data for NFTI is from March 5th, 2021, I choose all the historical data of each predictor from that specific data to June 27th, 2022 which includes 70 sets of weekly data in total. Since we use the log return of NFTI as the independent variable to compare the data for the week with the previous week which calculates the rate of return of NFTI investment, we only employ 69 weeks’ data in the model. For the weekly data, each week consists of 5 sections – open, high, low, close and volume. “Open” represents the opening price of the security which is the price of the first trades upon the opening of an exchange for that week. “High” and “Low” stand for the highest and lowest price of the index during the week. “Close” refers to the closing price which is the last price at which a stock trades during the week. “Volume” means sum of daily amount of trades during the week.
Based on the terms mentioned above, we select following data as predictors:
1) Log return of BTC: ln (closing price of the week/ the closing price of previous week) which calculates the rate of return of BTC investment. 2) BTC/NFTI: Ratio of BTC and NFTI based on the closing price of the previous week data. 3) NFTI spread: Closing price - Opening price of previous week data. 4) NFTI Volume/ NFTI Spread: ratio of two variables based on the previous week's data. 5) NFTI Volume/(close-open): ratio of NFTI volume and the difference between previous week’s closing price and opening price. 6) Global X cybersecurity ETF (BUG) weekly index, 7) Ethereum (ETH) weekly index and 8) KBW Nasdaq Bank (BKX) weekly index: three indexes are using the same week’s data as NFTI which are selected to see the correlation of NFTI to the global cybersecurity market, performance of the digital asset Ethereum and performance of the leading banks and thrifts in U.S. 9) ETH/NFTI: Ratio of ETH and NFTI based on the closing price of the previous week data. 10) Log return of ETH: to see the rate of return of ETH. 11) DeFi Pulse weekly Index: to examine correlation between NFTI and tokens' performance within the Decentralized Finance industry through using the same week’s data. 12) log return of Defi: to see the rate of return of Defi.

The goal is to predict log return of BTC by the suitable predictors from all the predictors mentioned above. Multivariate regression model would be suitable for this forecasting model. BTC and predictors about the trend of the NFT index might be suitable predictors.

Timeline: Collecting all the data for the first 3 weeks. Then start analyzing the data for the next two weeks. The rest of the time would be for improvement.

Questions: I have not learned techniques like best subset selection for selecting suitable predictors  in machine learning. I need to learn LSTM or maybe other techniques for this model.

